deploy:
  needs: build-push-image
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Login to GitHub Registry
      run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u calvinsaputra --password-stdin

    - name: Stop and remove container
      run: docker compose down --rmi all

    - name: Start container
      run: docker compose up -d

    - name: View container
      run: docker compose ps

    - name: Check container
      run: curl localhost:8080
